---
booktitle: Proceedings of the Twelth International Conference on Artificial Intelligence
  and Statistics
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
volume: 5
year: 2009
start: 2009-04-16
end: 2009-04-18
published: 2009-04-15
comments: false
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
shortname: AISTATS
bibsource: https://jmlr.csail.mit.edu/proceedings/
layout: proceedings
id: DykvWM2009
month: 0
cycles: false
editor:
- given: David
  family: Dyk
  prefix: van
- given: Max
  family: Welling
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Twelth International Conference on Artificial Intelligence and Statistics
    Held in Hilton Clearwater Beach Resort, Clearwater Beach, Florida USA on 16-18 April 2009

  Published as Volume 5 by the Proceedings of Machine Learning Research on 15 April 2009.

  Volume Edited by:
    David van Dyk
    Max Welling

  Series Editors:
    Neil D. Lawrence
date_str: 16--18 Apr
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v5"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v5
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Artificial Intelligence and Statistics
  url: http://www.ics.uci.edu/~aistats/
  location: Hilton Clearwater Beach Resort, Clearwater Beach, Florida USA
  dates:
  - 2009-04-16
  - 2009-04-17
  - 2009-04-18
  number: 12
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
